web:
  build: .
  command: python -u run.py
  environment:
    - SECRET_KEY = "this_is_the_secret"
    - APP_SETTINGS = "development"
  ports:
    - "5000:5000"
  volumes:
    - .:/dm
  links:
    - db
db:
  image: mongo:latest
  ports:
    - "27017:27017"